// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "iOSTestKit",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "NetworkStub", targets: ["NetworkStub"]),
        .library(name: "UITestHelpers", targets: ["UITestHelpers"]),
        .library(name: "TimeControl", targets: ["TimeControl"]),
        .library(name: "KeychainStore", targets: ["KeychainStore"]),
        .library(name: "CoreDataTestSupport", targets: ["CoreDataTestSupport"]),
        .library(name: "LocalNotifications", targets: ["LocalNotifications"]),
        .library(name: "SnapshotTesting", targets: ["SnapshotTesting"]),
        .library(name: "DeepLinkTesting", targets: ["DeepLinkTesting"]),
        .library(name: "LocationAuthorization", targets: ["LocationAuthorization"]),
        .library(name: "PurchaseSupport", targets: ["PurchaseSupport"]),
        .library(name: "DebugOverlay", targets: ["DebugOverlay"]),
        .library(name: "UserDefaultsStore", targets: ["UserDefaultsStore"]),
        .library(name: "PhotoLibraryAuthorization", targets: ["PhotoLibraryAuthorization"]),
        .library(name: "BiometricAuthentication", targets: ["BiometricAuthentication"]),
        .library(name: "PushRegistering", targets: ["PushRegistering"]),
        .library(name: "AppleSignIn", targets: ["AppleSignIn"]),
        .library(name: "BackgroundTaskScheduling", targets: ["BackgroundTaskScheduling"]),
        .library(name: "ContactsAuthorization", targets: ["ContactsAuthorization"]),
        .library(name: "NetworkReachabilityMonitoring", targets: ["NetworkReachabilityMonitoring"]),
        .library(name: "CloudKitAccountChecking", targets: ["CloudKitAccountChecking"]),
        .library(name: "ReviewRequesting", targets: ["ReviewRequesting"]),
        .library(name: "CameraAuthorization", targets: ["CameraAuthorization"]),
        .library(name: "MicrophoneAuthorization", targets: ["MicrophoneAuthorization"]),
        .library(name: "SpeechRecognitionAuthorization", targets: ["SpeechRecognitionAuthorization"]),
        .library(name: "CalendarAuthorization", targets: ["CalendarAuthorization"]),
        .library(name: "TrackingAuthorization", targets: ["TrackingAuthorization"]),
        .library(name: "AsyncSleeping", targets: ["AsyncSleeping"]),
        .library(name: "HealthAuthorization", targets: ["HealthAuthorization"]),
        .library(name: "MotionAuthorization", targets: ["MotionAuthorization"]),
        .library(name: "BluetoothAuthorization", targets: ["BluetoothAuthorization"]),
        .library(name: "SiriAuthorization", targets: ["SiriAuthorization"]),
        .library(name: "MediaLibraryAuthorization", targets: ["MediaLibraryAuthorization"]),
        .library(name: "DiagnosticReporting", targets: ["DiagnosticReporting"]),
        .library(name: "FeatureFlagging", targets: ["FeatureFlagging"]),
        .library(name: "AnalyticsLogging", targets: ["AnalyticsLogging"]),
        .library(name: "PowerStateProviding", targets: ["PowerStateProviding"]),
        .library(name: "BundleInfoProviding", targets: ["BundleInfoProviding"]),
        .library(name: "CellularDataRestrictionChecking", targets: ["CellularDataRestrictionChecking"]),
        .library(name: "AccessibilityStateProviding", targets: ["AccessibilityStateProviding"]),
        .library(name: "HapticFeedbackProviding", targets: ["HapticFeedbackProviding"]),
        .library(name: "IdleTimerControlling", targets: ["IdleTimerControlling"]),
        .library(name: "RemindersAuthorization", targets: ["RemindersAuthorization"]),
        .library(name: "LiveActivityAuthorization", targets: ["LiveActivityAuthorization"]),
        .library(name: "ClipboardProviding", targets: ["ClipboardProviding"]),
        .library(name: "FocusStatusAuthorization", targets: ["FocusStatusAuthorization"]),
        .library(name: "FamilyControlsAuthorization", targets: ["FamilyControlsAuthorization"]),
        .library(name: "JSONFixtureLoading", targets: ["JSONFixtureLoading"]),
        .library(name: "HomeKitAuthorization", targets: ["HomeKitAuthorization"]),
        .library(name: "WatchConnectivityStateProviding", targets: ["WatchConnectivityStateProviding"])
    ],
    targets: [
        .target(name: "NetworkStub"),
        .target(name: "UITestHelpers"),
        .target(name: "TimeControl"),
        .target(name: "KeychainStore"),
        .target(name: "CoreDataTestSupport"),
        .target(name: "LocalNotifications"),
        .target(name: "SnapshotTesting"),
        .target(name: "DeepLinkTesting"),
        .target(name: "LocationAuthorization"),
        .target(name: "PurchaseSupport"),
        .target(name: "DebugOverlay"),
        .target(name: "UserDefaultsStore"),
        .target(name: "PhotoLibraryAuthorization"),
        .target(name: "BiometricAuthentication"),
        .target(name: "PushRegistering"),
        .target(name: "AppleSignIn"),
        .target(name: "BackgroundTaskScheduling"),
        .target(name: "ContactsAuthorization"),
        .target(name: "NetworkReachabilityMonitoring"),
        .target(name: "CloudKitAccountChecking"),
        .target(name: "ReviewRequesting"),
        .target(name: "CameraAuthorization"),
        .target(name: "MicrophoneAuthorization"),
        .target(name: "SpeechRecognitionAuthorization"),
        .target(name: "CalendarAuthorization"),
        .target(name: "TrackingAuthorization"),
        .target(name: "AsyncSleeping"),
        .target(name: "HealthAuthorization"),
        .target(name: "MotionAuthorization"),
        .target(name: "BluetoothAuthorization"),
        .target(name: "SiriAuthorization"),
        .target(name: "MediaLibraryAuthorization"),
        .target(name: "DiagnosticReporting"),
        .target(name: "FeatureFlagging"),
        .target(name: "AnalyticsLogging"),
        .target(name: "PowerStateProviding"),
        .target(name: "BundleInfoProviding"),
        .target(name: "CellularDataRestrictionChecking"),
        .target(name: "AccessibilityStateProviding"),
        .target(name: "HapticFeedbackProviding"),
        .target(name: "IdleTimerControlling"),
        .target(name: "RemindersAuthorization"),
        .target(name: "LiveActivityAuthorization"),
        .target(name: "ClipboardProviding"),
        .target(name: "FocusStatusAuthorization"),
        .target(name: "FamilyControlsAuthorization"),
        .target(name: "JSONFixtureLoading"),
        .target(name: "HomeKitAuthorization"),
        .target(name: "WatchConnectivityStateProviding")
    ]
)
