// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "iOSTestKit",
    platforms: [.iOS(.v13), .macOS(.v13)],
    products: [
        .library(name: "NetworkStub", targets: ["NetworkStub"]),
        .library(name: "UITestHelpers", targets: ["UITestHelpers"]),
        .library(name: "TimeControl", targets: ["TimeControl"]),
        .library(name: "KeychainStore", targets: ["KeychainStore"]),
        .library(name: "CoreDataTestSupport", targets: ["CoreDataTestSupport"]),
        .library(name: "LocalNotifications", targets: ["LocalNotifications"]),
        .library(name: "SnapshotTesting", targets: ["SnapshotTesting"]),
        .library(name: "DeepLinkTesting", targets: ["DeepLinkTesting"]),
        .library(name: "LocationAuthorization", targets: ["LocationAuthorization"]),
        .library(name: "PurchaseSupport", targets: ["PurchaseSupport"]),
        .library(name: "DebugOverlay", targets: ["DebugOverlay"]),
        .library(name: "UserDefaultsStore", targets: ["UserDefaultsStore"]),
        .library(name: "PhotoLibraryAuthorization", targets: ["PhotoLibraryAuthorization"]),
        .library(name: "BiometricAuthentication", targets: ["BiometricAuthentication"]),
        .library(name: "PushRegistering", targets: ["PushRegistering"]),
        .library(name: "AppleSignIn", targets: ["AppleSignIn"]),
        .library(name: "BackgroundTaskScheduling", targets: ["BackgroundTaskScheduling"]),
        .library(name: "ContactsAuthorization", targets: ["ContactsAuthorization"]),
        .library(name: "NetworkReachabilityMonitoring", targets: ["NetworkReachabilityMonitoring"]),
        .library(name: "CloudKitAccountChecking", targets: ["CloudKitAccountChecking"]),
        .library(name: "ReviewRequesting", targets: ["ReviewRequesting"]),
        .library(name: "CameraAuthorization", targets: ["CameraAuthorization"]),
        .library(name: "MicrophoneAuthorization", targets: ["MicrophoneAuthorization"]),
        .library(name: "SpeechRecognitionAuthorization", targets: ["SpeechRecognitionAuthorization"]),
        .library(name: "CalendarAuthorization", targets: ["CalendarAuthorization"]),
        .library(name: "TrackingAuthorization", targets: ["TrackingAuthorization"]),
        .library(name: "AsyncSleeping", targets: ["AsyncSleeping"]),
        .library(name: "HealthAuthorization", targets: ["HealthAuthorization"]),
        .library(name: "MotionAuthorization", targets: ["MotionAuthorization"]),
        .library(name: "BluetoothAuthorization", targets: ["BluetoothAuthorization"]),
        .library(name: "SiriAuthorization", targets: ["SiriAuthorization"]),
        .library(name: "MediaLibraryAuthorization", targets: ["MediaLibraryAuthorization"]),
        .library(name: "DiagnosticReporting", targets: ["DiagnosticReporting"]),
        .library(name: "FeatureFlagging", targets: ["FeatureFlagging"]),
        .library(name: "AnalyticsLogging", targets: ["AnalyticsLogging"]),
        .library(name: "PowerStateProviding", targets: ["PowerStateProviding"]),
        .library(name: "BundleInfoProviding", targets: ["BundleInfoProviding"]),
        .library(name: "CellularDataRestrictionChecking", targets: ["CellularDataRestrictionChecking"]),
        .library(name: "AccessibilityStateProviding", targets: ["AccessibilityStateProviding"]),
        .library(name: "HapticFeedbackProviding", targets: ["HapticFeedbackProviding"]),
        .library(name: "IdleTimerControlling", targets: ["IdleTimerControlling"]),
        .library(name: "RemindersAuthorization", targets: ["RemindersAuthorization"]),
        .library(name: "LiveActivityAuthorization", targets: ["LiveActivityAuthorization"]),
        .library(name: "ClipboardProviding", targets: ["ClipboardProviding"]),
        .library(name: "FocusStatusAuthorization", targets: ["FocusStatusAuthorization"]),
        .library(name: "FamilyControlsAuthorization", targets: ["FamilyControlsAuthorization"]),
        .library(name: "JSONFixtureLoading", targets: ["JSONFixtureLoading"]),
        .library(name: "HomeKitAuthorization", targets: ["HomeKitAuthorization"]),
        .library(name: "WatchConnectivityStateProviding", targets: ["WatchConnectivityStateProviding"]),
        .library(name: "LocalizationCompletenessChecking", targets: ["LocalizationCompletenessChecking"]),
        .library(name: "MemoryLeakDetection", targets: ["MemoryLeakDetection"]),
        .library(name: "AsyncSequenceCollecting", targets: ["AsyncSequenceCollecting"]),
        .library(name: "WidgetTimelineTesting", targets: ["WidgetTimelineTesting"]),
        .library(name: "BatteryStateProviding", targets: ["BatteryStateProviding"]),
        .library(name: "SwiftDataTestSupport", targets: ["SwiftDataTestSupport"]),
        .library(name: "PasskeyAuthentication", targets: ["PasskeyAuthentication"]),
        .library(name: "ScreenCaptureStateProviding", targets: ["ScreenCaptureStateProviding"]),
        .library(name: "ProtectedDataAvailabilityProviding", targets: ["ProtectedDataAvailabilityProviding"]),
        .library(name: "DiskSpaceChecking", targets: ["DiskSpaceChecking"])
    ],
    targets: [
        .target(name: "NetworkStub"),
        .target(name: "UITestHelpers"),
        .target(name: "TimeControl"),
        .target(name: "KeychainStore"),
        .target(name: "CoreDataTestSupport"),
        .target(name: "LocalNotifications"),
        .target(name: "SnapshotTesting"),
        .target(name: "DeepLinkTesting"),
        .target(name: "LocationAuthorization"),
        .target(name: "PurchaseSupport"),
        .target(name: "DebugOverlay"),
        .target(name: "UserDefaultsStore"),
        .target(name: "PhotoLibraryAuthorization"),
        .target(name: "BiometricAuthentication"),
        .target(name: "PushRegistering"),
        .target(name: "AppleSignIn"),
        .target(name: "BackgroundTaskScheduling"),
        .target(name: "ContactsAuthorization"),
        .target(name: "NetworkReachabilityMonitoring"),
        .target(name: "CloudKitAccountChecking"),
        .target(name: "ReviewRequesting"),
        .target(name: "CameraAuthorization"),
        .target(name: "MicrophoneAuthorization"),
        .target(name: "SpeechRecognitionAuthorization"),
        .target(name: "CalendarAuthorization"),
        .target(name: "TrackingAuthorization"),
        .target(name: "AsyncSleeping"),
        .target(name: "HealthAuthorization"),
        .target(name: "MotionAuthorization"),
        .target(name: "BluetoothAuthorization"),
        .target(name: "SiriAuthorization"),
        .target(name: "MediaLibraryAuthorization"),
        .target(name: "DiagnosticReporting"),
        .target(name: "FeatureFlagging"),
        .target(name: "AnalyticsLogging"),
        .target(name: "PowerStateProviding"),
        .target(name: "BundleInfoProviding"),
        .target(name: "CellularDataRestrictionChecking"),
        .target(name: "AccessibilityStateProviding"),
        .target(name: "HapticFeedbackProviding"),
        .target(name: "IdleTimerControlling"),
        .target(name: "RemindersAuthorization"),
        .target(name: "LiveActivityAuthorization"),
        .target(name: "ClipboardProviding"),
        .target(name: "FocusStatusAuthorization"),
        .target(name: "FamilyControlsAuthorization"),
        .target(name: "JSONFixtureLoading"),
        .target(name: "HomeKitAuthorization"),
        .target(name: "WatchConnectivityStateProviding"),
        .target(name: "LocalizationCompletenessChecking"),
        .target(name: "MemoryLeakDetection"),
        .target(name: "AsyncSequenceCollecting"),
        .target(name: "WidgetTimelineTesting"),
        .target(name: "BatteryStateProviding"),
        .target(name: "SwiftDataTestSupport"),
        .target(name: "PasskeyAuthentication"),
        .target(name: "ScreenCaptureStateProviding"),
        .target(name: "ProtectedDataAvailabilityProviding"),
        .target(name: "DiskSpaceChecking"),

        // MARK: - Kit-only tests (macOS + iOS Simulator, run via `swift test`)
        .testTarget(name: "AnalyticsLoggingTests", dependencies: ["AnalyticsLogging"]),
        .testTarget(
            name: "AsyncSequenceCollectingTests",
            dependencies: ["AsyncSequenceCollecting"],
            resources: [.copy("Configuration.storekit")]
        ),
        .testTarget(name: "AsyncSleepingTests", dependencies: ["AsyncSleeping"]),
        .testTarget(name: "BiometricAuthenticationTests", dependencies: ["BiometricAuthentication"]),
        .testTarget(name: "BluetoothAuthorizationTests", dependencies: ["BluetoothAuthorization"]),
        .testTarget(name: "BundleInfoProvidingTests", dependencies: ["BundleInfoProviding"]),
        .testTarget(name: "CalendarAuthorizationTests", dependencies: ["CalendarAuthorization"]),
        .testTarget(name: "CameraAuthorizationTests", dependencies: ["CameraAuthorization"]),
        .testTarget(name: "CloudKitAccountCheckingTests", dependencies: ["CloudKitAccountChecking"]),
        .testTarget(name: "ContactsAuthorizationTests", dependencies: ["ContactsAuthorization"]),
        .testTarget(name: "DiskSpaceCheckingTests", dependencies: ["DiskSpaceChecking"]),
        .testTarget(name: "FeatureFlaggingTests", dependencies: ["FeatureFlagging"]),
        .testTarget(
            name: "JSONFixtureLoadingTests",
            dependencies: ["JSONFixtureLoading"],
            resources: [.copy("sample-fixture.json")]
        ),
        .testTarget(name: "KeychainStoreTests", dependencies: ["KeychainStore"]),
        .testTarget(
            name: "LocalizationCompletenessCheckingTests",
            dependencies: ["LocalizationCompletenessChecking"],
            resources: [.copy("sample-catalog.json")]
        ),
        .testTarget(name: "LocationAuthorizationTests", dependencies: ["LocationAuthorization"]),
        .testTarget(name: "MicrophoneAuthorizationTests", dependencies: ["MicrophoneAuthorization"]),
        .testTarget(name: "NetworkReachabilityMonitoringTests", dependencies: ["NetworkReachabilityMonitoring"]),
        .testTarget(name: "PhotoLibraryAuthorizationTests", dependencies: ["PhotoLibraryAuthorization"]),
        .testTarget(name: "PowerStateProvidingTests", dependencies: ["PowerStateProviding"]),
        .testTarget(
            name: "PurchaseSupportTests",
            dependencies: ["PurchaseSupport"],
            resources: [.copy("Configuration.storekit")]
        ),
        .testTarget(name: "RemindersAuthorizationTests", dependencies: ["RemindersAuthorization"]),
        .testTarget(name: "SpeechRecognitionAuthorizationTests", dependencies: ["SpeechRecognitionAuthorization"]),
        .testTarget(name: "SwiftDataTestSupportTests", dependencies: ["SwiftDataTestSupport"]),
        .testTarget(name: "UserDefaultsStoreTests", dependencies: ["UserDefaultsStore"]),

        // MARK: - Kit-only tests (iOS Simulator only)
        // Each file's content is wrapped in `#if os(iOS)`, matching the guard already
        // on the corresponding Sources/ module, so these build as empty targets under
        // plain `swift test` on macOS. `#if canImport(Framework)` looks tempting here
        // but is wrong for several of these frameworks (CoreMotion, Intents): the
        // module itself resolves fine on macOS, just missing the specific type this
        // kit needs, so `canImport` evaluates true and still fails to compile.
        // `#if os(iOS)` sidesteps that per-framework guessing entirely. Real
        // assertions only run via `xcodebuild test -scheme iOSTestKit-Package
        // -destination 'platform=iOS Simulator,name=...'` — see CONTRIBUTING.md.
        .testTarget(name: "AccessibilityStateProvidingTests", dependencies: ["AccessibilityStateProviding"]),
        .testTarget(name: "AppleSignInTests", dependencies: ["AppleSignIn"]),
        .testTarget(name: "BackgroundTaskSchedulingTests", dependencies: ["BackgroundTaskScheduling"]),
        .testTarget(name: "BatteryStateProvidingTests", dependencies: ["BatteryStateProviding"]),
        .testTarget(name: "CellularDataRestrictionCheckingTests", dependencies: ["CellularDataRestrictionChecking"]),
        .testTarget(name: "ClipboardProvidingTests", dependencies: ["ClipboardProviding"]),
        .testTarget(name: "DiagnosticReportingTests", dependencies: ["DiagnosticReporting"]),
        .testTarget(name: "FamilyControlsAuthorizationTests", dependencies: ["FamilyControlsAuthorization"]),
        .testTarget(name: "FocusStatusAuthorizationTests", dependencies: ["FocusStatusAuthorization"]),
        .testTarget(name: "HapticFeedbackProvidingTests", dependencies: ["HapticFeedbackProviding"]),
        .testTarget(name: "HealthAuthorizationTests", dependencies: ["HealthAuthorization"]),
        .testTarget(name: "HomeKitAuthorizationTests", dependencies: ["HomeKitAuthorization"]),
        .testTarget(name: "IdleTimerControllingTests", dependencies: ["IdleTimerControlling"]),
        .testTarget(name: "LiveActivityAuthorizationTests", dependencies: ["LiveActivityAuthorization"]),
        .testTarget(name: "MediaLibraryAuthorizationTests", dependencies: ["MediaLibraryAuthorization"]),
        .testTarget(name: "MotionAuthorizationTests", dependencies: ["MotionAuthorization"]),
        .testTarget(name: "PasskeyAuthenticationTests", dependencies: ["PasskeyAuthentication"]),
        .testTarget(name: "ProtectedDataAvailabilityProvidingTests", dependencies: ["ProtectedDataAvailabilityProviding"]),
        .testTarget(name: "PushRegisteringTests", dependencies: ["PushRegistering"]),
        .testTarget(name: "ReviewRequestingTests", dependencies: ["ReviewRequesting"]),
        .testTarget(name: "ScreenCaptureStateProvidingTests", dependencies: ["ScreenCaptureStateProviding"]),
        .testTarget(name: "SiriAuthorizationTests", dependencies: ["SiriAuthorization"]),
        .testTarget(name: "TrackingAuthorizationTests", dependencies: ["TrackingAuthorization"]),
        .testTarget(name: "WatchConnectivityStateProvidingTests", dependencies: ["WatchConnectivityStateProviding"])
    ]
)
